### ISSUE TITLE
Can't get it to work with Arduino Uno or Duemilanove

### ISSUE THREAD

**Issue by JoakimCh** [mikaelpatel/Arduino-TWI#5]
It's rather confusing to me what the problem is since it works with the Wire library.

I see that the address is not shifted the same direction though (in TWI.h), but it doesn't help changing that:
```c++
    Device(TWI& twi, uint8_t addr) :
      m_twi(twi),
      m_addr(addr << 1)
    {
    }
```
Here is most of my code:
```c++
#include <Arduino.h>
#include <Wire.h>
#define AVR
#include "TWI.h"
#include "Hardware/TWI.h"

Hardware::TWI twi;
TWI::Device dev{twi, 0x06};

  uint8_t read(uint8_t address, uint8_t register_, uint8_t bytesToRead, uint8_t* buffer) {
    if (!dev.acquire()) return 0;
    dev.write(&register_, sizeof(register_));
    delay(100);
    int8_t bytesRead = dev.read(buffer, bytesToRead);
    if (!dev.release() or bytesRead < 0) return 0;
    return bytesRead;
    /*
    Wire.beginTransmission(address >> 1);
    Wire.write(register_);
    uint8_t result = Wire.endTransmission();
    if (result == 0) {
      delay(100);
      bytesToRead = Wire.requestFrom(address >> 1, bytesToRead);
      return Wire.readBytes(buffer, bytesToRead);
    } else {
      Serial.print(F("err"));
      Serial.write(result);
    }
    return 0;
    */
  }
```

Edit: I forgot to mention what went wrong. 

Well, at first with some other code (not the one above) my Arduino kept resetting itself whenever I tried to use these functions. Which suggests memory overflow or something seriously wrong.

But with the code above the acquire never happens and if I remember correctly I think it then caused my Arduino to hang.

**Comment by mikaelpatel** [comment]
@JoakimCh Have you been able to run any of the examples? You should not include Wire.h.
